### ISSUE TITLE
Feature: System memory limit

### ISSUE THREAD

**Issue by SuperQ** [KimMachineGun/automemlimit#13]
# Proposal

Add system memory as an available provider in order to avoid OOMs when running outside of cgroups.

For workloads running outside of cgroups, or for systems without cgroups, it would be useful to have a provider that exposes the total system memory. This way you cold set a percent of system memory automatically as the limit.

**Comment by KimMachineGun** [comment]
Hi, @SuperQ.
Thank you for your proposal.

I think this proposal seems related to https://github.com/KimMachineGun/automemlimit/issues/4.
Is [this solution](https://github.com/KimMachineGun/automemlimit/issues/4#issuecomment-1833007327) using sigar api working for you?

**Comment by SuperQ** [comment]
Kinda, but I'm not sure that library is the most appropriate one to use. This would be imported into Prometheus, so I need to be somewhat careful about the dependency chain pulled in.

For example, the sigar library still pulls in the archived `github.com/pkg/errors` package.

**Comment by SuperQ** [comment]
I found https://github.com/pbnjay/memory, which is a much simpler library for getting system total memory.

**Comment by KimMachineGun** [comment]
@SuperQ 
Great! That library seems pretty solid.
I just released a pre-release version of that feature under the `v0.5.0-pre.3`, which respects system memory as a fallback.
You can use it with `AUTOMEMLIMIT_EXPERIMENT=system` for now, and after some time and getting more feedbacks on this feature, we can decide whether using it by default or not.

\+ If you want to use it without an environment variable, you can define your own provider like this.

```go
package main

import (
	"log/slog"
	"os"

	"github.com/KimMachineGun/automemlimit/memlimit"
	"github.com/pbnjay/memory"
)

func init() {
	memlimit.SetGoMemLimitWithOpts(
		memlimit.WithProvider(
			memlimit.ApplyFallback(
				memlimit.FromCgroup,
				FromSystem,
			),
		),
		memlimit.WithLogger(slog.New(slog.NewJSONHandler(os.Stderr, nil))),
	)
}

func main() {}

func FromSystem() (uint64, error) {
	limit := memory.TotalMemory()
	if limit == 0 {
		return 0, memlimit.ErrNoLimit
	}
	return limit, nil
}

```

**Comment by SuperQ** [comment]
Oh, strange, not sure why you're not putting these changes into `main`. Go modules don't pull from `main` unless you explicitly ask, so putting these changes into branches is a bit weird.

**Comment by SuperQ** [comment]
It will be a while before I can test this for real as the projects I work with won't support `log/slog` until Go 1.22. We match compiler support with the Go project.

**Comment by KimMachineGun** [comment]
@SuperQ 
The reason why I didn't push this feature to the main branch directly is that this feature is under development. I don't want to release a feature without enough time to test and get feedback. The `v0.5.0-pre.3` is for testing purposes.

But I can understand your concern about using the `log/slog` package, so I could release the experimental version of this feature first and then release the adaption of `log/slog` in the different minor version(maybe v0.6.0).

Maybe in the next release(`v0.5.0`), this feature is still in the experimental phase, so you should set `AUTOMEMLIMIT_EXPERIMENT=system` to turn on the system memory fallback.

\+ `fromSystem()` would be exported in the actual release.

**Comment by KimMachineGun** [comment]
> Maybe in the next release(v0.5.0), this feature will still be in the experimental phase, so you should set AUTOMEMLIMIT_EXPERIMENT=system to turn on the system memory fallback.

Does this make sense to you? If it is, I'll get into it and release `v0.5.0` after a few days of testing.

**Comment by SuperQ** [comment]
I'm already doing the setup with `memlimit.SetGoMemLimitWithOpts`.

See: https://github.com/prometheus/prometheus/compare/main...superq/automemlimit

Still need to plumb in a ratio flag.

I'm not a fan of using ENV vars to configure libraries like this. I would much prefer struct configs.

For example, rather than having logging built in, we implemented a stdlib compatible interface like this: https://pkg.go.dev/github.com/prometheus-community/pro-bing#Logger

Then in projects, you can pass any stdlib compatible logger. For example: https://pkg.go.dev/github.com/go-kit/log#NewStdlibAdapter

**Comment by KimMachineGun** [comment]
@SuperQ 
It's great to hear you are already doing that. Normally, I prefer not to use env to configure something. I prefer to use more explicit ways. But, sometimes, it could be helpful for the libraries that can affect the runtime behavior. I think this is the case.

By the way, I released (maybe) the last pre-release version of this feature under `v0.5.0-pre.4`, and I'll release it next week. It includes an experimental flag to enable system memory fallback and the exported `FromSystem` provider for those who need to use it directly.

Please check it one more time before the actual release.
I hope it will satisfy your needs.

**Comment by SuperQ** [comment]
Nice, I updated my test branch.

What do you think about adding a stdlog compatible logger interface?

**Comment by KimMachineGun** [comment]
Great!

\+ I'll leave some comments about the logger in your proposal.

**Comment by KimMachineGun** [comment]
@SuperQ 
Finally, `v0.5.0` was released!
Thank you for your proposal again.

As I mentioned earlier, after some time for evaluation, I will decide whether to enable it by default.

Please let me know if you have any further feedback.
