### ISSUE TITLE
Import gosigar for support more system?

### ISSUE THREAD

**Issue by okhowang** [KimMachineGun/automemlimit#4]
[gosigar](https://github.com/cloudfoundry/gosigar) can read total memory in many system. (include cgroup)
can we use it for support other system?

**Comment by mbyio** [comment]
Hey, I'd also be interested in this. Well, not necessarily sigar, but rather having automemlimit "just work" even outside a container.

For my use case, I am using Google Cloud run, and currently automemlimit doesn't work because it can't see it is running in a container. Specifically, I get the message

```
2023/04/23 01:40:07 failed to set GOMEMLIMIT: open /sys/fs/cgroup/cgroup.controllers: no such file or directory.
```

**Comment by KimMachineGun** [comment]
@mbyio 
Thank you for sharing that issue.
I'll take a look at it as soon as possible.

\+ I made a new issue #7 for the following communication.

**Comment by KimMachineGun** [comment]
Hi, @okhowang!
I apologize for the delay.

I created a sample project using the gosigar library as the primary provider and the cgroup provider as a fallback.
Please feel free to provide feedback.

https://github.com/KimMachineGun/automemlimit/tree/main/examples/gosigar

**Comment by KimMachineGun** [comment]
@okhowang 
I'll release the system memory fallback feature in the next release with another library, which seems simpler and generally used in other systems. So I'll close this issue. Please see https://github.com/KimMachineGun/automemlimit/issues/13 for further discussion.
